---
# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python versions to 2.7 and 3.6
python:
  - "2.7"
  - "3.6"

# Install the pip dependencies
install:
  - "pip install -q -r requirements.txt"
  - "pip install -q -r test-requirements.txt"

before_script:
  - "flake8 --max-line-length=100  --show-source --count ."

script:
  - "python setup.py test"

after_success:
  - "pytest --cov=./"
  - "codecov"